paths:
  jquery: 'jquery-1.10.2'
  bootstrap: 'bootstrap-3.1.1.min'
  'bootstrap-tagsinput': 'bootstrap-tagsinput-0.3.9'
  underscore: 'lodash.underscore-2.4.1'
  backbone: 'backbone-1.1.0'
  'backbone-modelbinder': 'backbone-modelbinder-1.0.5.min'
  'backbone-validation': 'backbone-validation-0.9.1'
  chaplin: 'chaplin-1.0.0'
  form2js: 'form2js'
  i18n: 'i18n'
shim:
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'backbone-modelbinder':
    deps: ['backbone']
    exports: 'Backbone.ModelBinder'
  'bootstrap':
    deps: ['jquery']
  'i18n':
    exports: 'I18n'
